### PR TITLE
Datatypes now cross platform compatible

### PR DESCRIPTION
**Pull request by lowjiajin**
Just switched out the datatypes as mentioned in #6. Tried looking in the `tests` folder for unit tests to verify correctness, but wasn't too sure what was the expected output of the `test_ncls.py` file.

As mentioned in the issue thread, I also had to delete `#include <sys/time.h>` for it to work on Windows, but am unsure if it affects CI, @endrebak replace it with something cross-platform compatible as you see fit :).

### CODE REVIEW

**Comment by lowjiajin** [comment]
@endrebak Do find the time to go through the PR! :)

**Comment by endrebak** [comment]
Will eventually, on vacation. Thanks!

**Comment by endrebak** [comment]
Sorry for forgetting this. You should have pinged me again 😂

**Comment by endrebak** [comment]
Thanks for the pr. I’ll add you to a contributors list :)

**Comment by endrebak** [comment]
Seems like it broke the build :/ Will have to revert.

**Comment by lowjiajin** [comment]
That’s odd, a few colleagues and I have been using it locally with no issues. I can look into it in a few weeks, as I’m now on holiday, haha.

**Comment by endrebak** [comment]
Cool. I will try to just remove time.h to begin with. I guess you are
testing win, not Linux :)

**Pull request merged**
